version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: simple_rh_nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/simple_rh/public
      - ./nginx/simple_rh.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    container_name: simple_rh_php
    volumes:
      - .:/var/www/simple_rh
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: simple_rh_db
    restart: always
    env_file:
        - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
