version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: simple_rh_nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/simple_rh/public
      - ./nginx/simple_rh.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    container_name: simple_rh_php
    volumes:
      - .:/var/www/simple_rh
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: simple_rh_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
